# Generated by Django 3.2.20 on 2023-10-23 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(default='', max_length=20)),
                ('user_email', models.EmailField(default='', max_length=20)),
                ('user_password', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='url_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(default='', max_length=20)),
                ('url_link', models.CharField(default='', max_length=280)),
                ('status_code', models.CharField(default='', max_length=20)),
                ('status_message', models.CharField(default='', max_length=80)),
                ('date_checked', models.DateField(verbose_name=datetime.datetime(2023, 10, 23, 21, 32, 8, 359350))),
            ],
        ),
    ]
