# Generated by Django 3.2.20 on 2023-10-23 20:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cronjob', '0002_auto_20231023_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login_model',
            name='user_email',
            field=models.EmailField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='url_model',
            name='date_checked',
            field=models.DateField(verbose_name=datetime.datetime(2023, 10, 23, 21, 43, 57, 683194)),
        ),
    ]
