# Generated by Django 3.2.20 on 2023-10-23 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cronjob', '0003_auto_20231023_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url_model',
            name='date_checked',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
